//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.15 at 11:14:22 AM CDT 
//


package com.johtull.selenium.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.johtull.selenium.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.johtull.selenium.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MappingRoot }
     * 
     */
    public MappingRoot createMappingRoot() {
        return new MappingRoot();
    }

    /**
     * Create an instance of {@link MappingRoot.MappingList }
     * 
     */
    public MappingRoot.MappingList createMappingRootMappingList() {
        return new MappingRoot.MappingList();
    }

    /**
     * Create an instance of {@link MappingRoot.MappingList.CatentryMapping }
     * 
     */
    public MappingRoot.MappingList.CatentryMapping createMappingRootMappingListCatentryMapping() {
        return new MappingRoot.MappingList.CatentryMapping();
    }

    /**
     * Create an instance of {@link MappingRoot.MappingList.CatentryMapping.ItemNames }
     * 
     */
    public MappingRoot.MappingList.CatentryMapping.ItemNames createMappingRootMappingListCatentryMappingItemNames() {
        return new MappingRoot.MappingList.CatentryMapping.ItemNames();
    }

}
